@startuml
class Submitter{
    + TaskAwaitable submitTask(const QueueTag& queueTag, void (*taskCallback) (VkQueue queue, VkFence fence, void* pData), void* pData)
    - std::vector<QueueGroupPool> queuePools
    - FencePool& fencePool
    - SubmitQueue& submitQueue
    - FenceWaitingQueue& fenceWaitingQueue
}

class QueueTag {
    std::vector<uint32_t> compatibleQueueGroupIDs
}

class QueueGroupPool {
    FreeQueuePool freeQueuePool
    TaskAwaitable submitQueue(void (*taskCallback) (VkQueue& queue, VkFence fence, void* pData), void* pData, TaskState& taskState))
}

class FreeQueuePool {
    + bool tryAcquire(VkQueue& queue)
    + void releaseQueue(VkQueue& queue)
}

enum State {
    WAITING_QUEUE
    ERROR
    PENDING
    DONE
}

class SubmitQueue {
    + void enqueue(void (*taskCallback) (VkQueue queue, VkFence fence, void* pData), void* pData, TaskState& taskState)
    + std::tuple<void (*taskCallback) (VkQueue queue, VkFence fence, void* pData), void* pData, TaskState& taskState> dequeue()
    + bool empty()
}

class FencePool {
    + void getFences(uint32_t count, std::vector<VkFence>& fenceBuffer)
    + void releaseFences(const std::vector<VkFence>& fenceBuffer)
}

class FenceWaitingQueue {
    + void enqueue(std::vector<VkFence>& fenceBuffer)
    + std::vector<std::tuple<VkFence, TaskState&>> dequeueFences()
    + bool empty()
}

class FenceWaiter {
    + void operator()()
    - void addNewFencesToLocalBuffer()
    - std::vector<VkFence> fenceLocalBuffer
    - QueuePool& queuePool
    - FenceWaitingQueue& fenceWaitingQueue
}

class Task {
    + TaskAwaitable createAwaitable()
    + void setCoroutineHandle(std::coroutine_handle handle, Executor* executor)
    - TaskState taskState
    - std::coroutine_handle coroHandle
    - Executor* executor
}

class TaskAwaitable {
    + TaskAwaitable(Task& task)
    + std::future<VkResult> getFuture()
    + void syncWait()
    + bool isDone()
}

class TaskAwaiter {
    + TaskAwaiter(TaskAwaitable&& awaitable, Executor* executor)
    + bool await_ready()
    + void await_suspend(std::coroutine_handle<> handle)
    + void await_resume()
}
@enduml